### ISSUE TITLE
Work out why MetaCPAN isn't indexing this module.

### ISSUE THREAD

**Issue by davorg** [davorg/tie-hash-cannabinol#1]
It's definitely there on MetaCPAN

https://metacpan.org/release/DAVECROSS/Tie-Hash-Cannabinol-1.11

But search doesn't find it

https://metacpan.org/search?q=tie%3A%3Ahash%3A%3Acannabinol&search_type=modules

And I'd expect this URL to work

https://metacpan.org/release/Tie-Hash-Cannabinol

And it's missing from my list of modules

https://metacpan.org/author/DAVECROSS

**Comment by MartinMcGrath** [comment]
Tie::Hash::Cannabinol does not show up in [02package.details.txt](http://www.cpan.org/modules/02packages.details.txt) which MetaCPAN [uses](https://metacpan.org/about/missing_modules).

**Comment by davorg** [comment]
Aha. And now I find a PAUSE email (from 2014!) explaining that it won't be indexed because I screwed up the version number somehow.

I'll dig deeper. Thanks.

**Comment by davorg** [comment]
Right. Managed to reindex the module, so it's now in [02package.details.txt](http://www.cpan.org/modules/02packages.details.txt). I guess it's a case of waiting for that to be picked up by MetaCPAN.

Thanks, again, for the help.

**Comment by davorg** [comment]
So that's fixed then. Sorry that you didn't get a pull request out of it :-)

**Comment by MartinMcGrath** [comment]
No problem, glad it's resolved :)
